version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: coffee-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: coffee_home
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: coffee123
      TZ: Asia/Ho_Chi_Minh
    command: ["postgres", "-c", "timezone=Asia/Ho_Chi_Minh", "-c", "log_timezone=Asia/Ho_Chi_Minh"]
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coffee -d coffee_home"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
